// THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.

import { Address, DataSourceTemplate, DataSourceContext } from '@graphprotocol/graph-ts'

export class AelinPool extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create('AelinPool', [address.toHex()])
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext('AelinPool', [address.toHex()], context)
  }
}

export class AelinDeal extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create('AelinDeal', [address.toHex()])
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext('AelinDeal', [address.toHex()], context)
  }
}

export class AelinUpfrontDeal extends DataSourceTemplate {
  static create(address: Address): void {
    DataSourceTemplate.create('AelinUpfrontDeal', [address.toHex()])
  }

  static createWithContext(address: Address, context: DataSourceContext): void {
    DataSourceTemplate.createWithContext('AelinUpfrontDeal', [address.toHex()], context)
  }
}
