name: Docker Build and Push

on: [push]

jobs:
  docker:
    name: Docker Subgraph Deployer Build
    runs-on: ubuntu-latest
    steps:
      - name: Private Actions Checkout
        uses: actions/checkout@v3

      - name: Docker Setup QEMU
        uses: docker/setup-qemu-action@v2

      - name: Docker Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker Login
        uses: docker/login-action@v2
        with:
          username: aelinprotocol
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ci/Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: aelinprotocol/subgraph-deployer:latest
          cache-from: type=registry,ref=aelinprotocol/subgraph-deployer:latest
          cache-to: type=inline,ref=aelinprotocol/subgraph-deployer:latest
